language: python
python:
  - "3.6"

install:
  - pip3 install rdflib
  - pip3 install pyformlang
  - pip3 install pydot
# command to run tests
script:
  - python3 -m unittest discover -s test -p '*_test.py'

