dist: bionic

language: python
python:
  - "3.6"
before_install:
  - sudo apt-get update
  - sudo apt-get install antlr4

install:
  - pip3 install -r requirements.txt

# command to run tests
script:
  - antlr4 -visitor -Dlanguage=Python3 -o gen/ query_languages/graph_query_grammar.g4
  - python3 -m unittest discover -s test -p '*_test.py'

